import io
import zipfile

def create_in_memory_zip(file_data: dict) -> bytes:
    """
    V2.0 Logic: Creates a ZIP where files contain AI-generated boilerplate.
    """
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path, content in file_data.items():
            # Clean path to prevent errors
            clean_path = path.strip().lstrip("/")
            
            # --- SUBTLE WATERMARK ---
            # We add a hidden signature at the top of every file
            header = f"\"\"\"\nGenerated by AI Project Architect\nAuthor: VishwarajKhatpe\nPath: {clean_path}\n\"\"\"\n\n"
            full_content = header + content
            
            # Write the real content to the ZIP
            zip_file.writestr(clean_path, full_content)
            
    zip_buffer.seek(0)
    return zip_buffer.getvalue()