import io
import zipfile
from typing import List

def create_in_memory_zip(file_paths: List[str]) -> bytes:
    """
    Creates a ZIP file entirely in RAM (memory) from a list of file paths.
    
    Args:
        file_paths (List[str]): A list of relative file paths (e.g., ['app/main.py', 'README.md'])
        
    Returns:
        bytes: The raw bytes of the ZIP file, ready for download.
    """
    # 1. Create a "virtual file" in memory (RAM buffer)
    zip_buffer = io.BytesIO()
    
    # 2. Open the ZipFile object using the memory buffer
    # compression=zipfile.ZIP_DEFLATED ensures the file size is small
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path in file_paths:
            # Clean the path to remove leading slashes or whitespaces
            clean_path = path.strip().lstrip("/")
            
            # We create a simple content string so the file isn't empty
            # In V2, we will put actual code here.
            file_content = f"# This file was generated by AI Architect\n# Path: {clean_path}\n"
            
            # Write the file into the ZIP archive
            # writestr handles writing data without needing a real file on disk
            zip_file.writestr(clean_path, file_content)
    
    # 3. Move the pointer to the start of the buffer
    zip_buffer.seek(0)
    
    # 4. Return the bytes value (the actual "file" data)
    return zip_buffer.getvalue()