import io
import zipfile

def create_in_memory_zip(file_data: dict) -> bytes:
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
        for path, content in file_data.items():
            # Safety Check: If content is NOT a string, force it to be one
            if not isinstance(content, str):
                content = str(content)

            clean_path = path.strip().lstrip("/")
            
            # Watermark
            header = f"\"\"\"\nGenerated by AI Project Architect\nAuthor: VishwarajKhatpe\nPath: {clean_path}\n\"\"\"\n\n"
            full_content = header + content
            
            zip_file.writestr(clean_path, full_content)
            
    zip_buffer.seek(0)
    return zip_buffer.getvalue()